EXECUTABLES = cg1_ex1_mac
CC=g++
CFLAGS= -O3 -DMACOSX
DEPS = node.h scenegraph.h robot.h context.h 
OBJ = node.o scenegraph.o robot.o context.o cg1_ex1.o
LIBS= -framework GLUT -framework OpenGL -lm

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

cg1_ex1_mac: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f *.o *~ $(EXECUTABLES)