EXECUTABLES = cg1_ex1
CC=g++
CFLAGS = -g -ggdb -Wall -O0
CXXFLAGS += $(CFLAGS)
DEPS = node.h scenegraph.h robot.h context.h 
OBJ = node.o scenegraph.o robot.o context.o cg1_ex1.o
LIBS = -lGLU -lGL -lglut -lm

%.o: %.c $(DEPS)
	$(CXX) $(CXXFLAGS) -o $@ -c $<

cg1_ex1: $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)

.PHONY: clean

clean:
	rm -f *.o *~ $(EXECUTABLES)
